---
services:
  
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  key-cloak:
      depends_on:
        - postgres
      profiles: ["non-started"]
      build:
        dockerfile: keycloak.Dockerfile
        context: '.'
        args:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
      entrypoint: "/opt/keycloak/bin/kc.sh"
      ports:
        - "5100:5100" # Http port
        - "5101:5101" # Https port
      working_dir: '/app'
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        DB_VENDOR: postgres
        DB_ADDR: postgres 
        DB_PORT: 5432
        DB_SCHEMA: keycloak_schema
        DB_DATABASE: postgres
        DB_USER: keycloak_user
        DB_PASSWORD: password

        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_PROXY: edge
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_URL: http://localhost:5100
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key.pem
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt.pem
      command: [
        "start-dev", # Starts the service in development mode
        "--http-port=5100",
        "--https-port=5101",
        "--https-certificate-file=/opt/keycloak/certs/tls.crt.pem",
        "--https-certificate-key-file=/opt/keycloak/certs/tls.key.pem",
        "--import-realm", # Tells it to import our config file on start up
        "--verbose"
        #"--log-level=debug", # enables debugging
        ]
      volumes:
          # Used for easily exporting and importing the configuration, uncomment to change config.
          - ./config:/opt/keycloak/data/import
