---
services:

  key-cloak:
      profiles: ["non-started"]
      build:
        context: '.'
        args:
            KEYCLOAK_CERT: ${KEYCLOAK_CERT}
            KEYCLOAK_CERT_KEY: ${KEYCLOAK_CERT_KEY}
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
      entrypoint: "/opt/keycloak/bin/kc.sh"
      ports:
        - "5100:5100" # Http port
        - "5101:5101" # Https port
      working_dir: '/app'
      environment:
        # KC_DB: mariadb
        # KC_DB_SCHEMA: keycloak
        # KC_DB_USERNAME: keycloak
        # KC_DB_PASSWORD: ${MARIADB_KEYCLOAK_PASSWORD:-keycloak}
        # KC_DB_URL_HOST: mariadb
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_PROXY: edge
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_URL: http://localhost:5100
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key.pem
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt.pem
      command: [
        "start-dev", # Starts the service in development mode
        "--http-port=5100",
        "--https-port=5101",
        "--https-certificate-file=/opt/keycloak/certs/tls.crt.pem",
        "--https-certificate-key-file=/opt/keycloak/certs/tls.key.pem",
        "--import-realm", # Tells it to import our config file on start up
        #"--log-level=debug", # enables debugging
        ]
      volumes:
          # Used for easily exporting and importing the configuration, uncomment to change config.
          - ./config:/opt/keycloak/data/import
